//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.33440
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace vpngui.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("vpngui.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to // Generated by CoffeeScript 1.7.1
        ///
        ////*
        ///  Copyright (c) 2014 clowwindy
        ///  
        ///  Permission is hereby granted, free of charge, to any person obtaining a copy
        ///  of this software and associated documentation files (the &quot;Software&quot;), to deal
        ///  in the Software without restriction, including without limitation the rights
        ///  to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
        ///  copies of the Software, and to permit persons to whom the Software is
        ///  furnished to do so, subject to the following condit [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string encrypt {
            get {
                return ResourceManager.GetString("encrypt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap green3 {
            get {
                object obj = ResourceManager.GetObject("green3", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap gui2 {
            get {
                object obj = ResourceManager.GetObject("gui2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to // The functions in source file is from phpjs
        ///// https://github.com/kvz/phpjs
        ///// See license below
        /////
        ///// Copyright (c) 2013 Kevin van Zonneveld (http://kvz.io) 
        ///// and Contributors (http://phpjs.org/authors)
        ///// 
        ///// Permission is hereby granted, free of charge, to any person obtaining a copy of
        ///// this software and associated documentation files (the &quot;Software&quot;), to deal in
        ///// the Software without restriction, including without limitation the rights to
        ///// use, copy, modify, merge, publish, distribute, sublic [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string inet {
            get {
                return ResourceManager.GetString("inet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to // Generated by CoffeeScript 1.7.1
        ///
        ////*
        ///  Copyright (c) 2014 clowwindy
        ///  
        ///  Permission is hereby granted, free of charge, to any person obtaining a copy
        ///  of this software and associated documentation files (the &quot;Software&quot;), to deal
        ///  in the Software without restriction, including without limitation the rights
        ///  to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
        ///  copies of the Software, and to permit persons to whom the Software is
        ///  furnished to do so, subject to the following condit [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string local {
            get {
                return ResourceManager.GetString("local", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to // Generated by CoffeeScript 1.7.1
        ///
        ////*
        ///  Copyright (c) 2014 clowwindy
        ///  
        ///  Permission is hereby granted, free of charge, to any person obtaining a copy
        ///  of this software and associated documentation files (the &quot;Software&quot;), to deal
        ///  in the Software without restriction, including without limitation the rights
        ///  to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
        ///  copies of the Software, and to permit persons to whom the Software is
        ///  furnished to do so, subject to the following condit [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string merge_sort {
            get {
                return ResourceManager.GetString("merge_sort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] node {
            get {
                object obj = ResourceManager.GetObject("node", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap red3 {
            get {
                object obj = ResourceManager.GetObject("red3", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] sslocal {
            get {
                object obj = ResourceManager.GetObject("sslocal", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to // Generated by CoffeeScript 1.7.1
        ///
        ////*
        ///  Copyright (c) 2014 clowwindy
        ///  
        ///  Permission is hereby granted, free of charge, to any person obtaining a copy
        ///  of this software and associated documentation files (the &quot;Software&quot;), to deal
        ///  in the Software without restriction, including without limitation the rights
        ///  to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
        ///  copies of the Software, and to permit persons to whom the Software is
        ///  furnished to do so, subject to the following condit [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string udprelay {
            get {
                return ResourceManager.GetString("udprelay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to // Generated by CoffeeScript 1.7.1
        ///
        ////*
        ///  Copyright (c) 2014 clowwindy
        ///  
        ///  Permission is hereby granted, free of charge, to any person obtaining a copy
        ///  of this software and associated documentation files (the &quot;Software&quot;), to deal
        ///  in the Software without restriction, including without limitation the rights
        ///  to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
        ///  copies of the Software, and to permit persons to whom the Software is
        ///  furnished to do so, subject to the following condit [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string utils {
            get {
                return ResourceManager.GetString("utils", resourceCulture);
            }
        }
    }
}
